version: '3.6'

services:

  # Create NMOS Registry/Controller container instance
  nmos-registry:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-registry
    hostname: nmos-registry
    domainname: local
    ports:
    - "80-81:80-81"
    - "1883:1883"
    volumes:
    - "./registry.json:/home/registry.json"
    environment:
    - RUN_NODE=FALSE
    networks:
      - default

  # Create NMOS Virtual Node container instance
  nmos-virtnode:
    image: rhastie/nmos-cpp:latest
    container_name: nmos-virtnode
    hostname: nmos-virtnode
    domainname: local
    ports:
    - "80-81:80-81"
    volumes:
    - "./node.json:/home/node.json"
    environment:
    - RUN_NODE=TRUE
    networks:
      - default
    depends_on:
    - nmos-registry    

  # Create AMWA NMOS Testing container instance
  nmos-testing:
    image: amwa/nmos-testing:latest
    container_name: nmos-testing
    hostname: nmos-testing
    domainname: local
    entrypoint: |
       /bin/bash -c "/etc/init.d/dbus start;
       /etc/init.d/avahi-daemon start;
       python3 nmos-test.py"
    ports:
    - "5000:5000"
    volumes:
    - "./UserConfig.py:/config/UserConfig.py"
    networks:
      - default
    depends_on:
    - nmos-virtnode


networks:
  default:
    driver: bridge
